### PR TITLE
Fixing not initialized whiteboxCounter for map tab in Puntland.

### PR DESCRIPTION
**Pull request by tomeksabala**

### CODE REVIEW

**Comment by tomeksabala** [comment]
That's correct. Usually the ajax call happens inside `<script>` tag directly in html file. This `mapManager` however was not initialising `whiteboxCounter` on it own but probably was depending on some other piece of js code. This js code must not have been executed in Puntland configuration.
Also I have done some logic simplification only touching function `drawMap` internals.

**Comment by tomeksabala** [comment]
@jonathansberry Why have you closed this?

**Comment by jonathansberry** [comment]
I accidentally merged all changes from this commit in with this PR: 
https://github.com/meerkat-code/meerkat_frontend/pull/421
I needed the changes to get the mapping to work, then forgot to separate before merging into development. Aware there are obviously better ways to do this, sorry.

**Comment by tomeksabala** [comment]
Haha. Right. Thanks.

**Pull request closed without merging**
